---
services:
  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      #- N8N_HOST=n8n.${APP_DOMAIN}
      #- N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_RUNNERS_ENABLED=true
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.${APP_DOMAIN}/
      - GENERIC_TIMEZONE=Etc/UTC
      - TZ=America/Costa_Rica
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.n8n-secure.tls=true"
      - "traefik.http.routers.n8n-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.n8n-secure.service=n8n"
      - "traefik.http.routers.n8n-secure.entrypoints=https"
      - "traefik.http.routers.n8n-secure.rule=Host(`n8n.${APP_DOMAIN}`)"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"

volumes:
  n8n_data:

networks:
  proxy:
    external: true
